name: e_commerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^6.2.0
  go_router: ^16.3.0
  font_awesome_flutter: ^10.12.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
# flutter_assets:
#   assets_path: assets/images/
#   output_path: lib/core/constants/
#   filename: app_assets.dart
#   field_prefix: null
#   classname: AppAssets
#   ignore_comments: true
